// automatically generated by the FlatBuffers compiler, do not modify

package com.anyonehub.abl.cache.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ScannedMetadataFbs extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { /* patched */ }
  public static ScannedMetadataFbs getRootAsScannedMetadataFbs(ByteBuffer _bb) { return getRootAsScannedMetadataFbs(_bb, new ScannedMetadataFbs()); }
  public static ScannedMetadataFbs getRootAsScannedMetadataFbs(ByteBuffer _bb, ScannedMetadataFbs obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ScannedMetadataFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String targetClass() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer targetClassAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer targetClassInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public boolean isModule() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean isCompileTarget() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String entryPoints(int j) { int o = __offset(10); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int entryPointsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public StringVector entryPointsVector() { return entryPointsVector(new StringVector()); }
  public StringVector entryPointsVector(StringVector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String injectableProperties(int j) { int o = __offset(12); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int injectablePropertiesLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public StringVector injectablePropertiesVector() { return injectablePropertiesVector(new StringVector()); }
  public StringVector injectablePropertiesVector(StringVector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public boolean injectableConstructorParameters() { int o = __offset(14); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createScannedMetadataFbs(FlatBufferBuilder builder,
      int targetClassOffset,
      boolean isModule,
      boolean isCompileTarget,
      int entryPointsOffset,
      int injectablePropertiesOffset,
      boolean injectableConstructorParameters) {
    builder.startTable(6);
    ScannedMetadataFbs.addInjectableProperties(builder, injectablePropertiesOffset);
    ScannedMetadataFbs.addEntryPoints(builder, entryPointsOffset);
    ScannedMetadataFbs.addTargetClass(builder, targetClassOffset);
    ScannedMetadataFbs.addInjectableConstructorParameters(builder, injectableConstructorParameters);
    ScannedMetadataFbs.addIsCompileTarget(builder, isCompileTarget);
    ScannedMetadataFbs.addIsModule(builder, isModule);
    return ScannedMetadataFbs.endScannedMetadataFbs(builder);
  }

  public static void startScannedMetadataFbs(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addTargetClass(FlatBufferBuilder builder, int targetClassOffset) { builder.addOffset(0, targetClassOffset, 0); }
  public static void addIsModule(FlatBufferBuilder builder, boolean isModule) { builder.addBoolean(1, isModule, false); }
  public static void addIsCompileTarget(FlatBufferBuilder builder, boolean isCompileTarget) { builder.addBoolean(2, isCompileTarget, false); }
  public static void addEntryPoints(FlatBufferBuilder builder, int entryPointsOffset) { builder.addOffset(3, entryPointsOffset, 0); }
  public static int createEntryPointsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEntryPointsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addInjectableProperties(FlatBufferBuilder builder, int injectablePropertiesOffset) { builder.addOffset(4, injectablePropertiesOffset, 0); }
  public static int createInjectablePropertiesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startInjectablePropertiesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addInjectableConstructorParameters(FlatBufferBuilder builder, boolean injectableConstructorParameters) { builder.addBoolean(5, injectableConstructorParameters, false); }
  public static int endScannedMetadataFbs(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ScannedMetadataFbs get(int j) { return get(new ScannedMetadataFbs(), j); }
    public ScannedMetadataFbs get(ScannedMetadataFbs obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

