// automatically generated by the FlatBuffers compiler, do not modify

package com.anyonehub.abl.cache.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SymbolCacheTable extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { /* patched */ }
  public static SymbolCacheTable getRootAsSymbolCacheTable(ByteBuffer _bb) { return getRootAsSymbolCacheTable(_bb, new SymbolCacheTable()); }
  public static SymbolCacheTable getRootAsSymbolCacheTable(ByteBuffer _bb, SymbolCacheTable obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SymbolCacheTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.anyonehub.abl.cache.fbs.ScannedMetadataFbs metadata(int j) { return metadata(new com.anyonehub.abl.cache.fbs.ScannedMetadataFbs(), j); }
  public com.anyonehub.abl.cache.fbs.ScannedMetadataFbs metadata(com.anyonehub.abl.cache.fbs.ScannedMetadataFbs obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int metadataLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public com.anyonehub.abl.cache.fbs.ScannedMetadataFbs.Vector metadataVector() { return metadataVector(new com.anyonehub.abl.cache.fbs.ScannedMetadataFbs.Vector()); }
  public com.anyonehub.abl.cache.fbs.ScannedMetadataFbs.Vector metadataVector(com.anyonehub.abl.cache.fbs.ScannedMetadataFbs.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createSymbolCacheTable(FlatBufferBuilder builder,
      int metadataOffset) {
    builder.startTable(1);
    SymbolCacheTable.addMetadata(builder, metadataOffset);
    return SymbolCacheTable.endSymbolCacheTable(builder);
  }

  public static void startSymbolCacheTable(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addMetadata(FlatBufferBuilder builder, int metadataOffset) { builder.addOffset(0, metadataOffset, 0); }
  public static int createMetadataVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMetadataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endSymbolCacheTable(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishSymbolCacheTableBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedSymbolCacheTableBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SymbolCacheTable get(int j) { return get(new SymbolCacheTable(), j); }
    public SymbolCacheTable get(SymbolCacheTable obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

